# Training parameters
learning_rate: 0.001
epochs: 500
adjustment_scale: 0.01

# Cost function weights
lambda1: 0.5  # Weight for average set size
lambda2: 0.5  # Weight for abstention rate

# Initial hyperparameters
alpha: 0.1    # Initial error rate parameter
beta: 0.05    # Initial abstention rate parameter
cum_prob_threshold: 0.9  # Initial cumulative probability threshold

# Data parameters
cal_ratio: 0.5  # Calibration set ratio
